peg :: Peg
	= s:spaces d:definition p:peg	{ cons d p }
	/ 	{ empty }
;
definition :: Definition
	= v:variable s:spaces c:[isColon] c:[isColon] s:spaces t:typ s:spaces e:[isEqual] s:spaces sel:selection s:spaces s:[isSemi]	{ mkDef v t sel }
;
selection :: Selection
	= ex:expressionHs s:spaces e:[isSlash] s:spaces sel:selection	{ cons ex sel }
	/ ex:expressionHs	{ cons ex empty }
;
expressionHs :: ExpressionHs
	= e:expression s:spaces o:[isOpenWave] s:spaces h:hsExp s:spaces c:[isCloseWave]	{ mkExpressionHs e h }
;
expression :: Expression
	= l:nameLeaf s:spaces e:expression	{ cons l e }
	/ 	{ empty }
;
nameLeaf :: NameLeaf
	= n:variable c:[isColon] l:leaf	{ mkNameLeaf n l }
;
leaf :: Leaf
	= t:test	{ left t }
	/ v:variable	{ right v }
;
test :: ExR
	= o:[isOpenBr] h:hsExp c:[isCloseBr]	{ getEx h }
;
hsExp :: Ex
	= v:variable s:spaces h:hsExp	{ apply v h }
	/ v:variable	{ toExp v }
;
typ :: String
	= u:upper t:tail	{ cons u t }
;
variable :: String
	= l:lower t:tail	{ cons l t }
;
tail :: String
	= a:alpha t:tail	{ cons a t }
	/ 	{ empty }
;
alpha :: Char
	= u:upper	{ u }
	/ l:lower	{ l }
;
upper :: Char
	= u:[isUpper]	{ u }
;
lower :: Char
	= l:[isLower]	{ l }
;
digit :: Char
	= d:[isDigit]	{ d }
;
symbolOne :: Char
	= sym:[isSymbolOne]	{ sym }
;
symbolTwo :: Char
	= sym:[isSymbolTwo]	{ sym }
;
spaces :: Nil
	= s:space ss:spaces	{ nil }
	/ 	{ nil }
;
space :: Nil
	= l:[isSpace]	{ nil }
;
